/*
Mailchimp Marketing API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.55
Contact: apihelp@mailchimp.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailchimpmarketingapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type ConnectedSitesAPI interface {

	/*
	DeleteConnectedSitesId Delete connected site

	Remove a connected site from your Mailchimp account.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param connectedSiteId The unique identifier for the site.
	@return ConnectedSitesAPIDeleteConnectedSitesIdRequest
	*/
	DeleteConnectedSitesId(ctx context.Context, connectedSiteId string) ConnectedSitesAPIDeleteConnectedSitesIdRequest

	// DeleteConnectedSitesIdExecute executes the request
	DeleteConnectedSitesIdExecute(r ConnectedSitesAPIDeleteConnectedSitesIdRequest) (*http.Response, error)

	/*
	GetConnectedSites List connected sites

	Get all connected sites in an account.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ConnectedSitesAPIGetConnectedSitesRequest
	*/
	GetConnectedSites(ctx context.Context) ConnectedSitesAPIGetConnectedSitesRequest

	// GetConnectedSitesExecute executes the request
	//  @return ConnectedSites
	GetConnectedSitesExecute(r ConnectedSitesAPIGetConnectedSitesRequest) (*ConnectedSites, *http.Response, error)

	/*
	GetConnectedSitesId Get connected site

	Get information about a specific connected site.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param connectedSiteId The unique identifier for the site.
	@return ConnectedSitesAPIGetConnectedSitesIdRequest
	*/
	GetConnectedSitesId(ctx context.Context, connectedSiteId string) ConnectedSitesAPIGetConnectedSitesIdRequest

	// GetConnectedSitesIdExecute executes the request
	//  @return ConnectedSite
	GetConnectedSitesIdExecute(r ConnectedSitesAPIGetConnectedSitesIdRequest) (*ConnectedSite, *http.Response, error)

	/*
	PostConnectedSites Add connected site

	Create a new Mailchimp connected site.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ConnectedSitesAPIPostConnectedSitesRequest
	*/
	PostConnectedSites(ctx context.Context) ConnectedSitesAPIPostConnectedSitesRequest

	// PostConnectedSitesExecute executes the request
	//  @return ConnectedSite
	PostConnectedSitesExecute(r ConnectedSitesAPIPostConnectedSitesRequest) (*ConnectedSite, *http.Response, error)

	/*
	PostConnectedSitesIdActionsVerifyScriptInstallation Verify connected site script

	Verify that the connected sites script has been installed, either via the script URL or fragment.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param connectedSiteId The unique identifier for the site.
	@return ConnectedSitesAPIPostConnectedSitesIdActionsVerifyScriptInstallationRequest
	*/
	PostConnectedSitesIdActionsVerifyScriptInstallation(ctx context.Context, connectedSiteId string) ConnectedSitesAPIPostConnectedSitesIdActionsVerifyScriptInstallationRequest

	// PostConnectedSitesIdActionsVerifyScriptInstallationExecute executes the request
	PostConnectedSitesIdActionsVerifyScriptInstallationExecute(r ConnectedSitesAPIPostConnectedSitesIdActionsVerifyScriptInstallationRequest) (*http.Response, error)
}

// ConnectedSitesAPIService ConnectedSitesAPI service
type ConnectedSitesAPIService service

type ConnectedSitesAPIDeleteConnectedSitesIdRequest struct {
	ctx context.Context
	ApiService ConnectedSitesAPI
	connectedSiteId string
}

func (r ConnectedSitesAPIDeleteConnectedSitesIdRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteConnectedSitesIdExecute(r)
}

/*
DeleteConnectedSitesId Delete connected site

Remove a connected site from your Mailchimp account.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param connectedSiteId The unique identifier for the site.
 @return ConnectedSitesAPIDeleteConnectedSitesIdRequest
*/
func (a *ConnectedSitesAPIService) DeleteConnectedSitesId(ctx context.Context, connectedSiteId string) ConnectedSitesAPIDeleteConnectedSitesIdRequest {
	return ConnectedSitesAPIDeleteConnectedSitesIdRequest{
		ApiService: a,
		ctx: ctx,
		connectedSiteId: connectedSiteId,
	}
}

// Execute executes the request
func (a *ConnectedSitesAPIService) DeleteConnectedSitesIdExecute(r ConnectedSitesAPIDeleteConnectedSitesIdRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ConnectedSitesAPIService.DeleteConnectedSitesId")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/connected-sites/{connected_site_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"connected_site_id"+"}", url.PathEscape(parameterValueToString(r.connectedSiteId, "connectedSiteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ProblemDetailDocument
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ConnectedSitesAPIGetConnectedSitesRequest struct {
	ctx context.Context
	ApiService ConnectedSitesAPI
	fields *[]string
	excludeFields *[]string
	count *int32
	offset *int32
}

// A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.
func (r ConnectedSitesAPIGetConnectedSitesRequest) Fields(fields []string) ConnectedSitesAPIGetConnectedSitesRequest {
	r.fields = &fields
	return r
}

// A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.
func (r ConnectedSitesAPIGetConnectedSitesRequest) ExcludeFields(excludeFields []string) ConnectedSitesAPIGetConnectedSitesRequest {
	r.excludeFields = &excludeFields
	return r
}

// The number of records to return. Default value is 10. Maximum value is 1000
func (r ConnectedSitesAPIGetConnectedSitesRequest) Count(count int32) ConnectedSitesAPIGetConnectedSitesRequest {
	r.count = &count
	return r
}

// Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this it the number of records from a collection to skip. Default value is 0.
func (r ConnectedSitesAPIGetConnectedSitesRequest) Offset(offset int32) ConnectedSitesAPIGetConnectedSitesRequest {
	r.offset = &offset
	return r
}

func (r ConnectedSitesAPIGetConnectedSitesRequest) Execute() (*ConnectedSites, *http.Response, error) {
	return r.ApiService.GetConnectedSitesExecute(r)
}

/*
GetConnectedSites List connected sites

Get all connected sites in an account.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ConnectedSitesAPIGetConnectedSitesRequest
*/
func (a *ConnectedSitesAPIService) GetConnectedSites(ctx context.Context) ConnectedSitesAPIGetConnectedSitesRequest {
	return ConnectedSitesAPIGetConnectedSitesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ConnectedSites
func (a *ConnectedSitesAPIService) GetConnectedSitesExecute(r ConnectedSitesAPIGetConnectedSitesRequest) (*ConnectedSites, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ConnectedSites
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ConnectedSitesAPIService.GetConnectedSites")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/connected-sites"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fields", r.fields, "csv")
	}
	if r.excludeFields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", r.excludeFields, "csv")
	}
	if r.count != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "count", r.count, "")
	} else {
		var defaultValue int32 = 10
		r.count = &defaultValue
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "")
	} else {
		var defaultValue int32 = 0
		r.offset = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ProblemDetailDocument
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ConnectedSitesAPIGetConnectedSitesIdRequest struct {
	ctx context.Context
	ApiService ConnectedSitesAPI
	connectedSiteId string
	fields *[]string
	excludeFields *[]string
}

// A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.
func (r ConnectedSitesAPIGetConnectedSitesIdRequest) Fields(fields []string) ConnectedSitesAPIGetConnectedSitesIdRequest {
	r.fields = &fields
	return r
}

// A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.
func (r ConnectedSitesAPIGetConnectedSitesIdRequest) ExcludeFields(excludeFields []string) ConnectedSitesAPIGetConnectedSitesIdRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r ConnectedSitesAPIGetConnectedSitesIdRequest) Execute() (*ConnectedSite, *http.Response, error) {
	return r.ApiService.GetConnectedSitesIdExecute(r)
}

/*
GetConnectedSitesId Get connected site

Get information about a specific connected site.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param connectedSiteId The unique identifier for the site.
 @return ConnectedSitesAPIGetConnectedSitesIdRequest
*/
func (a *ConnectedSitesAPIService) GetConnectedSitesId(ctx context.Context, connectedSiteId string) ConnectedSitesAPIGetConnectedSitesIdRequest {
	return ConnectedSitesAPIGetConnectedSitesIdRequest{
		ApiService: a,
		ctx: ctx,
		connectedSiteId: connectedSiteId,
	}
}

// Execute executes the request
//  @return ConnectedSite
func (a *ConnectedSitesAPIService) GetConnectedSitesIdExecute(r ConnectedSitesAPIGetConnectedSitesIdRequest) (*ConnectedSite, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ConnectedSite
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ConnectedSitesAPIService.GetConnectedSitesId")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/connected-sites/{connected_site_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"connected_site_id"+"}", url.PathEscape(parameterValueToString(r.connectedSiteId, "connectedSiteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fields", r.fields, "csv")
	}
	if r.excludeFields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", r.excludeFields, "csv")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ProblemDetailDocument
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ConnectedSitesAPIPostConnectedSitesRequest struct {
	ctx context.Context
	ApiService ConnectedSitesAPI
	body *ConnectedSite1
}

func (r ConnectedSitesAPIPostConnectedSitesRequest) Body(body ConnectedSite1) ConnectedSitesAPIPostConnectedSitesRequest {
	r.body = &body
	return r
}

func (r ConnectedSitesAPIPostConnectedSitesRequest) Execute() (*ConnectedSite, *http.Response, error) {
	return r.ApiService.PostConnectedSitesExecute(r)
}

/*
PostConnectedSites Add connected site

Create a new Mailchimp connected site.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ConnectedSitesAPIPostConnectedSitesRequest
*/
func (a *ConnectedSitesAPIService) PostConnectedSites(ctx context.Context) ConnectedSitesAPIPostConnectedSitesRequest {
	return ConnectedSitesAPIPostConnectedSitesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ConnectedSite
func (a *ConnectedSitesAPIService) PostConnectedSitesExecute(r ConnectedSitesAPIPostConnectedSitesRequest) (*ConnectedSite, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ConnectedSite
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ConnectedSitesAPIService.PostConnectedSites")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/connected-sites"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ProblemDetailDocument
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ConnectedSitesAPIPostConnectedSitesIdActionsVerifyScriptInstallationRequest struct {
	ctx context.Context
	ApiService ConnectedSitesAPI
	connectedSiteId string
}

func (r ConnectedSitesAPIPostConnectedSitesIdActionsVerifyScriptInstallationRequest) Execute() (*http.Response, error) {
	return r.ApiService.PostConnectedSitesIdActionsVerifyScriptInstallationExecute(r)
}

/*
PostConnectedSitesIdActionsVerifyScriptInstallation Verify connected site script

Verify that the connected sites script has been installed, either via the script URL or fragment.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param connectedSiteId The unique identifier for the site.
 @return ConnectedSitesAPIPostConnectedSitesIdActionsVerifyScriptInstallationRequest
*/
func (a *ConnectedSitesAPIService) PostConnectedSitesIdActionsVerifyScriptInstallation(ctx context.Context, connectedSiteId string) ConnectedSitesAPIPostConnectedSitesIdActionsVerifyScriptInstallationRequest {
	return ConnectedSitesAPIPostConnectedSitesIdActionsVerifyScriptInstallationRequest{
		ApiService: a,
		ctx: ctx,
		connectedSiteId: connectedSiteId,
	}
}

// Execute executes the request
func (a *ConnectedSitesAPIService) PostConnectedSitesIdActionsVerifyScriptInstallationExecute(r ConnectedSitesAPIPostConnectedSitesIdActionsVerifyScriptInstallationRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ConnectedSitesAPIService.PostConnectedSitesIdActionsVerifyScriptInstallation")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/connected-sites/{connected_site_id}/actions/verify-script-installation"
	localVarPath = strings.Replace(localVarPath, "{"+"connected_site_id"+"}", url.PathEscape(parameterValueToString(r.connectedSiteId, "connectedSiteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ProblemDetailDocument
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
