/*
Mailchimp Marketing API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.0.55
Contact: apihelp@mailchimp.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailchimpmarketingapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type TemplateFoldersAPI interface {

	/*
	DeleteTemplateFoldersId Delete template folder

	Delete a specific template folder, and mark all the templates in the folder as 'unfiled'.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param folderId The unique id for the template folder.
	@return TemplateFoldersAPIDeleteTemplateFoldersIdRequest
	*/
	DeleteTemplateFoldersId(ctx context.Context, folderId string) TemplateFoldersAPIDeleteTemplateFoldersIdRequest

	// DeleteTemplateFoldersIdExecute executes the request
	DeleteTemplateFoldersIdExecute(r TemplateFoldersAPIDeleteTemplateFoldersIdRequest) (*http.Response, error)

	/*
	GetTemplateFolders List template folders

	Get all folders used to organize templates.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return TemplateFoldersAPIGetTemplateFoldersRequest
	*/
	GetTemplateFolders(ctx context.Context) TemplateFoldersAPIGetTemplateFoldersRequest

	// GetTemplateFoldersExecute executes the request
	//  @return TemplateFolders
	GetTemplateFoldersExecute(r TemplateFoldersAPIGetTemplateFoldersRequest) (*TemplateFolders, *http.Response, error)

	/*
	GetTemplateFoldersId Get template folder

	Get information about a specific folder used to organize templates.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param folderId The unique id for the template folder.
	@return TemplateFoldersAPIGetTemplateFoldersIdRequest
	*/
	GetTemplateFoldersId(ctx context.Context, folderId string) TemplateFoldersAPIGetTemplateFoldersIdRequest

	// GetTemplateFoldersIdExecute executes the request
	//  @return TemplateFolder
	GetTemplateFoldersIdExecute(r TemplateFoldersAPIGetTemplateFoldersIdRequest) (*TemplateFolder, *http.Response, error)

	/*
	PatchTemplateFoldersId Update template folder

	Update a specific folder used to organize templates.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param folderId The unique id for the template folder.
	@return TemplateFoldersAPIPatchTemplateFoldersIdRequest
	*/
	PatchTemplateFoldersId(ctx context.Context, folderId string) TemplateFoldersAPIPatchTemplateFoldersIdRequest

	// PatchTemplateFoldersIdExecute executes the request
	//  @return TemplateFolder
	PatchTemplateFoldersIdExecute(r TemplateFoldersAPIPatchTemplateFoldersIdRequest) (*TemplateFolder, *http.Response, error)

	/*
	PostTemplateFolders Add template folder

	Create a new template folder.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return TemplateFoldersAPIPostTemplateFoldersRequest
	*/
	PostTemplateFolders(ctx context.Context) TemplateFoldersAPIPostTemplateFoldersRequest

	// PostTemplateFoldersExecute executes the request
	//  @return TemplateFolder
	PostTemplateFoldersExecute(r TemplateFoldersAPIPostTemplateFoldersRequest) (*TemplateFolder, *http.Response, error)
}

// TemplateFoldersAPIService TemplateFoldersAPI service
type TemplateFoldersAPIService service

type TemplateFoldersAPIDeleteTemplateFoldersIdRequest struct {
	ctx context.Context
	ApiService TemplateFoldersAPI
	folderId string
}

func (r TemplateFoldersAPIDeleteTemplateFoldersIdRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteTemplateFoldersIdExecute(r)
}

/*
DeleteTemplateFoldersId Delete template folder

Delete a specific template folder, and mark all the templates in the folder as 'unfiled'.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param folderId The unique id for the template folder.
 @return TemplateFoldersAPIDeleteTemplateFoldersIdRequest
*/
func (a *TemplateFoldersAPIService) DeleteTemplateFoldersId(ctx context.Context, folderId string) TemplateFoldersAPIDeleteTemplateFoldersIdRequest {
	return TemplateFoldersAPIDeleteTemplateFoldersIdRequest{
		ApiService: a,
		ctx: ctx,
		folderId: folderId,
	}
}

// Execute executes the request
func (a *TemplateFoldersAPIService) DeleteTemplateFoldersIdExecute(r TemplateFoldersAPIDeleteTemplateFoldersIdRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TemplateFoldersAPIService.DeleteTemplateFoldersId")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/template-folders/{folder_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"folder_id"+"}", url.PathEscape(parameterValueToString(r.folderId, "folderId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ProblemDetailDocument
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type TemplateFoldersAPIGetTemplateFoldersRequest struct {
	ctx context.Context
	ApiService TemplateFoldersAPI
	fields *[]string
	excludeFields *[]string
	count *int32
	offset *int32
}

// A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.
func (r TemplateFoldersAPIGetTemplateFoldersRequest) Fields(fields []string) TemplateFoldersAPIGetTemplateFoldersRequest {
	r.fields = &fields
	return r
}

// A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.
func (r TemplateFoldersAPIGetTemplateFoldersRequest) ExcludeFields(excludeFields []string) TemplateFoldersAPIGetTemplateFoldersRequest {
	r.excludeFields = &excludeFields
	return r
}

// The number of records to return. Default value is 10. Maximum value is 1000
func (r TemplateFoldersAPIGetTemplateFoldersRequest) Count(count int32) TemplateFoldersAPIGetTemplateFoldersRequest {
	r.count = &count
	return r
}

// Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination), this it the number of records from a collection to skip. Default value is 0.
func (r TemplateFoldersAPIGetTemplateFoldersRequest) Offset(offset int32) TemplateFoldersAPIGetTemplateFoldersRequest {
	r.offset = &offset
	return r
}

func (r TemplateFoldersAPIGetTemplateFoldersRequest) Execute() (*TemplateFolders, *http.Response, error) {
	return r.ApiService.GetTemplateFoldersExecute(r)
}

/*
GetTemplateFolders List template folders

Get all folders used to organize templates.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return TemplateFoldersAPIGetTemplateFoldersRequest
*/
func (a *TemplateFoldersAPIService) GetTemplateFolders(ctx context.Context) TemplateFoldersAPIGetTemplateFoldersRequest {
	return TemplateFoldersAPIGetTemplateFoldersRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return TemplateFolders
func (a *TemplateFoldersAPIService) GetTemplateFoldersExecute(r TemplateFoldersAPIGetTemplateFoldersRequest) (*TemplateFolders, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TemplateFolders
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TemplateFoldersAPIService.GetTemplateFolders")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/template-folders"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fields", r.fields, "csv")
	}
	if r.excludeFields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", r.excludeFields, "csv")
	}
	if r.count != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "count", r.count, "")
	} else {
		var defaultValue int32 = 10
		r.count = &defaultValue
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "")
	} else {
		var defaultValue int32 = 0
		r.offset = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ProblemDetailDocument
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type TemplateFoldersAPIGetTemplateFoldersIdRequest struct {
	ctx context.Context
	ApiService TemplateFoldersAPI
	folderId string
	fields *[]string
	excludeFields *[]string
}

// A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.
func (r TemplateFoldersAPIGetTemplateFoldersIdRequest) Fields(fields []string) TemplateFoldersAPIGetTemplateFoldersIdRequest {
	r.fields = &fields
	return r
}

// A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation.
func (r TemplateFoldersAPIGetTemplateFoldersIdRequest) ExcludeFields(excludeFields []string) TemplateFoldersAPIGetTemplateFoldersIdRequest {
	r.excludeFields = &excludeFields
	return r
}

func (r TemplateFoldersAPIGetTemplateFoldersIdRequest) Execute() (*TemplateFolder, *http.Response, error) {
	return r.ApiService.GetTemplateFoldersIdExecute(r)
}

/*
GetTemplateFoldersId Get template folder

Get information about a specific folder used to organize templates.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param folderId The unique id for the template folder.
 @return TemplateFoldersAPIGetTemplateFoldersIdRequest
*/
func (a *TemplateFoldersAPIService) GetTemplateFoldersId(ctx context.Context, folderId string) TemplateFoldersAPIGetTemplateFoldersIdRequest {
	return TemplateFoldersAPIGetTemplateFoldersIdRequest{
		ApiService: a,
		ctx: ctx,
		folderId: folderId,
	}
}

// Execute executes the request
//  @return TemplateFolder
func (a *TemplateFoldersAPIService) GetTemplateFoldersIdExecute(r TemplateFoldersAPIGetTemplateFoldersIdRequest) (*TemplateFolder, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TemplateFolder
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TemplateFoldersAPIService.GetTemplateFoldersId")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/template-folders/{folder_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"folder_id"+"}", url.PathEscape(parameterValueToString(r.folderId, "folderId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "fields", r.fields, "csv")
	}
	if r.excludeFields != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "exclude_fields", r.excludeFields, "csv")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ProblemDetailDocument
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type TemplateFoldersAPIPatchTemplateFoldersIdRequest struct {
	ctx context.Context
	ApiService TemplateFoldersAPI
	folderId string
	body *TemplateFolder1
}

func (r TemplateFoldersAPIPatchTemplateFoldersIdRequest) Body(body TemplateFolder1) TemplateFoldersAPIPatchTemplateFoldersIdRequest {
	r.body = &body
	return r
}

func (r TemplateFoldersAPIPatchTemplateFoldersIdRequest) Execute() (*TemplateFolder, *http.Response, error) {
	return r.ApiService.PatchTemplateFoldersIdExecute(r)
}

/*
PatchTemplateFoldersId Update template folder

Update a specific folder used to organize templates.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param folderId The unique id for the template folder.
 @return TemplateFoldersAPIPatchTemplateFoldersIdRequest
*/
func (a *TemplateFoldersAPIService) PatchTemplateFoldersId(ctx context.Context, folderId string) TemplateFoldersAPIPatchTemplateFoldersIdRequest {
	return TemplateFoldersAPIPatchTemplateFoldersIdRequest{
		ApiService: a,
		ctx: ctx,
		folderId: folderId,
	}
}

// Execute executes the request
//  @return TemplateFolder
func (a *TemplateFoldersAPIService) PatchTemplateFoldersIdExecute(r TemplateFoldersAPIPatchTemplateFoldersIdRequest) (*TemplateFolder, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TemplateFolder
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TemplateFoldersAPIService.PatchTemplateFoldersId")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/template-folders/{folder_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"folder_id"+"}", url.PathEscape(parameterValueToString(r.folderId, "folderId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ProblemDetailDocument
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type TemplateFoldersAPIPostTemplateFoldersRequest struct {
	ctx context.Context
	ApiService TemplateFoldersAPI
	body *TemplateFolder1
}

func (r TemplateFoldersAPIPostTemplateFoldersRequest) Body(body TemplateFolder1) TemplateFoldersAPIPostTemplateFoldersRequest {
	r.body = &body
	return r
}

func (r TemplateFoldersAPIPostTemplateFoldersRequest) Execute() (*TemplateFolder, *http.Response, error) {
	return r.ApiService.PostTemplateFoldersExecute(r)
}

/*
PostTemplateFolders Add template folder

Create a new template folder.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return TemplateFoldersAPIPostTemplateFoldersRequest
*/
func (a *TemplateFoldersAPIService) PostTemplateFolders(ctx context.Context) TemplateFoldersAPIPostTemplateFoldersRequest {
	return TemplateFoldersAPIPostTemplateFoldersRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return TemplateFolder
func (a *TemplateFoldersAPIService) PostTemplateFoldersExecute(r TemplateFoldersAPIPostTemplateFoldersRequest) (*TemplateFolder, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TemplateFolder
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TemplateFoldersAPIService.PostTemplateFolders")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/template-folders"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v ProblemDetailDocument
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
